### ISSUE TITLE
Symmetry values differ based on the color of the image

### ISSUE THREAD

**Issue by mls453** [stm/rquantae#2]
When testing out the img_symmetry function, I noticed that the symmetry values change depending on the colors of the image (same when the different colored images are converted to grayscale).  Is there a way to enforce exact matches based on color, so that the relative colors don't influence the score?  

The 5% shift is also great, though I wonder if it would also be useful to be able to rotate the axis of symmetry, such that one would get a line that is most symmetrical for the image (e.g. if a dominant feature in the image is tilted to the left, it would fit a line to that symmetry, and give a score for the symmetry along that line).

**Comment by stm** [comment]
Symmetry and color are a bit tricky. As I understand it, your goal is to have a metric of how similar two image halves are,  but only based on their color. Thus, the two images below should result in the same symmetry values.

<img width="150" alt="img_red" src="https://user-images.githubusercontent.com/238118/138744136-8c3d2f64-6d47-4e5d-aa19-6226de12285d.png">&numsp;<img width="150" alt="img_blue" src="https://user-images.githubusercontent.com/238118/138744144-a01bdf6e-b06e-4684-8cff-91e82e2639d6.png">

The following code results in horizontal symmetry values of 0.99 for both images. The steps are:
1. first convert the RGB images into the HSV color space (hue, saturation, value)
2. then only use the information on the hue channel (i.e., the color information)
3. in the final step, calculate the percentage of the hue values being identical in the image halves

This approach could also be extended to incorporate e.g. the saturation into this measure (by having a weighted mean, for example).

```
# load image
img_red <- imagefluency::img_read("img_red.png") # change accordingly

# vertical symmetry (left vs right)
img <- OpenImageR::RGB_to_HSV(img_red)[,,1] # keep only HUE
# OpenImageR::imageShow(img)

imgW <- dim(img)[2] # image width
stimL <- img[, 1:floor(imgW / 2)] # left image half
stimR <- img[, imgW:(1 + ceiling(imgW / 2))] # right image half (flipped!)

# vectorize matrices
pixL <- as.vector(stimL)
pixR <- as.vector(stimR)

# estimate percentage of pixels being identical
mean(pixL == pixR)

# -- Note: if you want to allow for a little bit of noise in the image,
#          define a noise threshold and compare the pixel differences against
#          this threshold
noise = .01
mean(abs(pixL - pixR) < noise)


# horizontal symmetry (top vs bottom)
# -- Note: here, we just rotate the image by 90 degrees, thereby allowing to
#          remain the rest of the code the same
img = OpenImageR::RGB_to_HSV(imagefluency::rotate90(img_red))[,,1] # keep only HUE

imgW <- dim(img)[2]
stimL <- img[, 1:floor(imgW / 2)]
stimR <- img[, imgW:(1 + ceiling(imgW / 2))]

pixL <- as.vector(stimL)
pixR <- as.vector(stimR)

mean(pixL == pixR)
```

As for the rotation of the symmetry axis: I completely agree, this would be a nice feature. Unfortunately, this is not trivial. I may incorporate this option in the future.
