### ISSUE TITLE
Error: Invalid input (should be a matrix or a 3-dimensional array of numeric or integer values)

### ISSUE THREAD

**Issue by FelipeMAffonso** [stm/rquantae#5]
Hello,

I'm trying to generate the symmetry, self-similarity, and contrast values (simplicity and complexity work fine!), but I'm getting this error: Error: Invalid input (should be a matrix or a 3-dimensional array of numeric or integer values)

It's weird because it's working just fine with simplicity. But there's some error that doesn't allow the other functions to work. Can you help me? Also, the pictures I'm using work on the shiny app. So I suspect it's something with R.

Thanks

**Comment by FelipeMAffonso** [comment]
It doesn't make a lot of sense. Why the input, which is a path to an image, would be a matrix or 3d array of numeric or integer values?

**Comment by FelipeMAffonso** [comment]
Nevermind. I wasn't using the img_read command. I was just putting the path on it. If I use img_read it works. Thanks for this nice package.

**Comment by stm** [comment]
Thanks for your feedback, Felipe. Maybe I'll have to update the documentation to highlight more that you cannot directly use paths (so far) but need to use `img_read()` first.

**Comment by FelipeMAffonso** [comment]
I think that's a good idea. I got confused because the path worked for simplicity, but not for the others. But also it's not a big deal - the vignettes clearly show the img_read code.
